name = "polymart-telegram"
main = "src/index.ts"
compatibility_date = "2025-01-26"

compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "MONEY_MADE"
id = "1b57bac7b1304e8c84cac51a6c25d598"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[observability.logs]
enabled = true

[triggers]
crons = ["* * * * *"]